### ISSUE TITLE
mac m1 电脑 docker-connector.conf 文件路径是 /opt/homebrew/etc

### ISSUE THREAD

**Issue by superxieshushu** [wenjunxiao/mac-docker-connector#5]

**Comment by superxieshushu** [comment]
$ docker network ls --filter driver=bridge --format "{{.ID}}" | xargs docker network inspect --format "route {{range .IPAM.Config}}{{.Subnet}}{{end}}" >> /usr/local/etc/docker-connector.conf 这条命令是不是考虑区分一下？

**Comment by wenjunxiao** [comment]
> $ docker network ls --filter driver=bridge --format "{{.ID}}" | xargs docker network inspect --format "route {{range .IPAM.Config}}{{.Subnet}}{{end}}" >> /usr/local/etc/docker-connector.conf 这条命令是不是考虑区分一下？

是个好主意。不过，在安装的成功的时候会提示配置文件的路径以及以上操作命令，因此准备文档中会注释以安装成功之后的提示信息为主，避免由于homebrew的位置调整而引起文档不准确

**Comment by jaccoh** [comment]
he is correct. .. althought I read only english.. /usr/local is not always /usr/local .. for me its /opt/homebrew.. but there is this variable you can use:

HOMEBREW_PREFIX

(environment variable)

**Comment by wenjunxiao** [comment]
> he is correct. .. althought I read only english.. /usr/local is not always /usr/local .. for me its /opt/homebrew.. but there is this variable you can use:
> 
> HOMEBREW_PREFIX
> 
> (environment variable)

Yes, it's not always `/usr/local`. I use the variable `HOMEBREW_PREFIX` in installer script [docker-connector.rb](https://github.com/wenjunxiao/homebrew-brew/blob/master/Formula/docker-connector.rb), and it works fine. But, I cannot use the variable `HOMEBREW_PREFIX` in my `iTerm`, because of the variable is undefined.
So, I think `$(brew --prefix)` may be the best answer, it will print the default prefix of homebrew.
